apiVersion: v1
kind: ConfigMap
metadata:
  name: model-config
  namespace: iris-ml
  labels:
    app.kubernetes.io/name: iris-ml
data:
  MODEL_VERSION: "1.0.0"
  MODEL_PATH: "/app/models/model.pkl"
  STORAGE_ACCOUNT: ""
  STORAGE_CONTAINER: "models"
  MODEL_BLOB_NAME: "iris-classifier/v1.0.0/model.pkl"
