apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iris-ml

resources:
  - common
  - api-gateway
  - inference-service

commonLabels:
  app.kubernetes.io/part-of: iris-ml-platform
  app.kubernetes.io/managed-by: kustomize
