# ============================================
# ArgoCD Image Updater - Kustomization
# Instala e configura o Image Updater
# ============================================
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  # Instalacao oficial do Image Updater
  - https://raw.githubusercontent.com/argoproj-labs/argocd-image-updater/v0.12.2/manifests/install.yaml

  # Configuracoes customizadas
  - configmap.yaml
  - secret-acr.yaml
